import { Pizza } from './pizza'


export const PIZZAS: Pizza[] = [
    {
        id: 1,
        name: 'Margherita',
        price: 9.50,
        numberOrdered: 0,
        totalAmountProduct: 0,
    },
    {
        id: 2,
        name: 'Calzone',
        price: 12.75,
        numberOrdered: 0,
        totalAmountProduct: 0,
    },
    {
        id: 3,
        name: 'Bresaola',
        price: 16.90,
        numberOrdered: 0,
        totalAmountProduct: 0,
    },
    {
        id: 4,
        name: 'Hawaï',
        price: 12.75,
        numberOrdered: 0,
        totalAmountProduct: 0,
    },
    {
        id: 5,
        name: 'Alla salsiccia',
        price: 15.75,
        numberOrdered: 0,
        totalAmountProduct: 0,
    },
    {
        id: 6,
        name: 'Zucchine e pancetta',
        price: 14.00, numberOrdered: 0,
        totalAmountProduct: 0,
    },
    {
        id: 7,
        name: '4 formaggi',
        price: 12.75,
        numberOrdered: 0,
        totalAmountProduct: 0,
    },
    {
        id: 8,
        name: 'Antipasta',
        price: 13.90,
        numberOrdered: 0,
        totalAmountProduct: 0,
    },
    {
        id: 9,
        name: 'Bismark',
        price: 15.75,
        numberOrdered: 0,
        totalAmountProduct: 0,
    },
    {
        id: 10,
        name: 'Frutti di mare',
        price: 13.90,
        numberOrdered: 0,
        totalAmountProduct: 0,
    },
    {
        id: 11,
        name: 'Amore',
        price: 13.90,
        numberOrdered: 0,
        totalAmountProduct: 0,
    },
    {
        id: 12,
        name: 'Capricciosa',
        price: 13.75,
        numberOrdered: 0,
        totalAmountProduct: 0,
    },
    {
        id: 13,
        name: '4 saisons',
        price: 13.90,
        numberOrdered: 0,
        totalAmountProduct: 0,
    },
    {
        id: 14,
        name: 'Prosciuto',
        price: 14.90,
        numberOrdered: 0,
        totalAmountProduct: 0,
    },
    {
        id: 15,
        name: 'Saporita',
        price: 16.90,
        numberOrdered: 0,
        totalAmountProduct: 0,
    },
    {
        id: 16,
        name: 'Delizia',
        price: 14.90,
        numberOrdered: 0,
        totalAmountProduct: 0,
    },
    {
        id: 17,
        name: 'Burrata',
        price: 13.90,
        numberOrdered: 0,
        totalAmountProduct: 0,
    },
]
